spring:
  application:
    name: gateway-service
server:
  port: 8765
zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignored-services: '*'
  routes:
    user-service:
      path: /users/**
      serviceId: user-service
      stripPrefix: false
    content-service:
      path: /contents/**
      serviceId: content-service
      stripPrefix: false

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false