create table user_roles
(
    user_id bigint not null,
    role    varchar(255)
);

create table users
(
    id              bigint generated by default as identity (start with 1),
    created_date    timestamp            not null,
    updated_date    timestamp,
    last_login_date timestamp,
    email           varchar(100) unique  not null,
    password        varchar(100)         not null,
    first_name      varchar(255),
    last_name       varchar(255),
    gender          varchar(20)          not null,
    phone           varchar(50),
    image_uuid      varchar(255),
    enabled         boolean default true not null,
    primary key (id)
);

alter table user_roles
    add constraint user_roles_idx foreign key (user_id) references users on delete cascade;

insert into users
values (1, now(), null, null, 'admin@gmail.com', '$2y$12$qn9/9CJAoRefjK/wu6S.jOXp.EYNXnw0A3EYAVzUPwD6Iz7QBtz1m', 'admin', 'admin', 'MALE', '+7-777-888-9900', null, true),
       (2, now(), null, null, 'user@gmail.com', '$2y$12$qn9/9CJAoRefjK/wu6S.jOXp.EYNXnw0A3EYAVzUPwD6Iz7QBtz1m', 'user', 'user', 'FEMALE', '+8-555-333-1234', null, true),
       (3, now(), null, null, 'manager@gmail.com', '$2y$12$qn9/9CJAoRefjK/wu6S.jOXp.EYNXnw0A3EYAVzUPwD6Iz7QBtz1m', 'manager', 'manager', 'CUSTOM', '+8-800-555-3535', null, true);

INSERT INTO USER_ROLES (role, user_id)
VALUES ('ROLE_ADMIN', 1),
       ('ROLE_CLIENT', 1),
       ('ROLE_CLIENT', 2),
       ('ROLE_MANAGER', 3);