create table user_roles
(
    user_id bigint not null,
    role    varchar(255)
);

create table users
(
    id              bigint generated by default as identity (start with 1),
    created_date    timestamp            not null,
    updated_date    timestamp,
    last_login_date timestamp,
    email           varchar(100) unique  not null,
    password        varchar(100)         not null,
    first_name      varchar(255),
    last_name       varchar(255),
    gender          varchar(20),
    phone           varchar(50),
    image_url      varchar(255),
    enabled         boolean default true not null,
    oauth_client_id varchar(255) unique,
    provider        varchar(20),
    primary key (id)
);

alter table user_roles
    add constraint user_roles_idx foreign key (user_id) references users on delete cascade;
